---
title: "Leaflet"
output: html_document
---
```{r}
# install.packages("pxR")
# install.packages("sorvi", repos="http://R-Forge.R-project.org")
 

wmshist <- "https://io.apps.fao.org/geoserver/wms/ASIS/HDF/v2?version=1.3.0"
layerhist <- "HDF"

wmsfao <- "https://io.apps.fao.org/geoserver/wms/ASIS/HDF/v1?version=1.3.0"

layer_crop_season1_30p <- "HDF_C_S1_LA30:ASIS:asis_hdf_c"
layer_crop_season1_50p <- "HDF_C_S1_LA50:ASIS:asis_hdf_c"
layer_crop_season2_30p <- "HDF_C_S2_LA30:ASIS:asis_hdf_c"
layer_crop_season2_50p <- "HDF_C_S2_LA50:ASIS:asis_hdf_c"


library("leaflet")
library("sp")
```


```{r}
# this example from the tutorial works
leaflet() %>% 
  addTiles() %>% 
  setView(lat = 13.7167, lng = -88.8602, zoom = 9) %>% 
  addWMSTiles(
    wmshist,
    layers = layerhist,
    options = WMSTileOptions(format = "image/png", transparent = TRUE) 
)


# wmshist1 <- PreprocessWMS(url = LoadWMSurl(provider = "OIVA", service = "Corine"))
# 
# test <- sorvi::GetWMSraster(wmshist1, 
#                             layerhist, 
#                             extent = polyLevel2_sf , 
#                             resolution = 25)
```