---
title: "Methodology for Area Characterisation"
date: " `r format(Sys.Date(),  '%d %B %Y')`"
output: 
  html_document: 
    toc: yes
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Methodology for Area Characterisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Recent displacement trends show growing numbers of displaced population living outside of designated areas such as camp/camp like setting (traditional camps collective/transit/reception centres, informal settlements) with a majority setting in dispersed locations predominately urban and peri-urban areas such as informal settlements, unfinished buildings or interspersed in host community homes and communities, shared rooms or rental arrangements. To be able to reach, properly assess and understand local dynamics, vulnerabilities and capacities of the displaced and host populations alike, humanitarian organisations are increasingly using sub-national [Area Based Approach](https://www.humanitarianlibrary.org/collection/implementing-area-based-approaches). Area based approaches define "*an area, rather than a sector or target group, as a primary entry point*". Such approach is particularly appropriate when residents in an affected area face complex, inter-related and multisectoral needs, resulting in risk of forced displacement.

# Area Based Approach for Forced Displacement: Characterisation through Sensor Data

In the context of migration statistics, forced displacement is often analyzed with the prism of [push and pull factors](https://immigrationforum.org/article/push-or-pull-factors-what-drives-central-american-migrants-to-the-u-s/).

+----------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
|                                                                                                    | **Push Factor** (Mitigated by intervention to address root causes within countries of origin)        | **Pull Factor** (Mitigated by migration & Asylum policies of receiving countries) |
+====================================================================================================+======================================================================================================+===================================================================================+
| **Economic Dimension** (Addressed by programme in relation with development & poverty alleviation) | Lack of public services, Unemployement, Overpopulation                                               | More jobs, Better jobs, Higher wages, promise of a "better individual life"       |
+----------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| **Social Dimension** (Addressed by programme in relation with protection)                          | Violence, insecurity, intolerance towards certain groups, active political or religious persecution, | Safety, tolerance, freedom                                                        |
+----------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| **Environmental Dimension** (Addressed by programme in relation with resilience & sustainability)  | Climate change, natural disasters                                                                    | More livable environment                                                          |
+----------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+

Though, traditional statistical data sources are often lacking sufficient geographically-fine-grained disaggregation to inform sub national scale approach and characterization. Alternative based on sophisticated index like [Inform Colombia](https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Subnational-Risk/Colombia) requires extensive expert consultations and might not fully reflect the important dimension to be reflected in the context of forced displacement and migration.

# Proposed methodology

New sensors provide unique abilities to capture new flow of information from social medias (Anonymized data from Facebook platform) at subnational scale through grid level information. Satellite data can pick up signals of economic activity by detecting light at night, it can pick up development status by detecting infrastructure such as roads, and it can pick up signals for individual household wealth by detecting different building footprints and roof types.

In regard to the framework above, an initial selection of globally available layers includes:

-   Economics:

    -   Weighted Relative Wealth Index ([Facebook-RWI](https://data.humdata.org/dataset/relative-wealth-index))
    -   Social Connectedness Index ([Facebook-SCI](https://data.humdata.org/dataset/social-connectedness-index))
    -   Public Services Catchment area (OSM)

-   Environment:

    -   Agricultural drought frequency Index ([FAO-ASI](http://www.fao.org/giews/earthobservation/country/index.jsp?code=SLV&lang=en))
    -   Climatic Natural Risk - Flood and Cyclone (Prevention Web)
    -   Geologic Natural Risk - Earthquake and Volcano (Prevention Web)

-   Social:

    -   Population Dependency Ratio (Facebook)
    -   Movement Range data sets [Facebook](https://data.humdata.org/dataset/movement-range-maps)
    -   Violence (ACLED)

Information can be compiled and aggregated at admin level 2 in order to build composite Indicators. Different areas can be then grouped together based on the values from those composite indicators. The advantage of this approach are multiple: 1. **Granularity**: Optimal Level of granularity 2. **Availibility**: Data Consistently and freely available worldwide, simplicity to obtain information, ensor based indicators are potentially less sensitive to political pressure 3. **Reproducibility**: Can be used in multiple countries easily and Fully automated and audited through reproducible analysis script

The resulting information can complement other traditional source of information both on quantitative (Household Survey) and qualitative (Focus Group Discussions) side.

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      collapse = FALSE,
                      comment = "#>",
                      fig.align = "center")
knitr::opts_chunk$set(fig.width = 12, fig.height = 9, fig.retina = 2, fig.align = "center", dev.args = list(pointsize = 11))
set.seed(1)
extrafont::loadfonts(quiet=TRUE)
options(scipen = 999) # turn-off scientific notation like 1e+48
library(unhcRstyle)
library(magrittr)
library(readr)
library(sf)
library(purrr)
library(lubridate)
library(dplyr)
library(GADMTools)
library(tidyverse)
library(gghighlight)
library(dplyr)
library(zoo)
library(raster)
library(sf)
library(leaflet)
library(sp)
library(glue)
library(exactextractr)
library(furrr)
library(rmapshaper)
library(magick)
library(magrittr) 
library(mapsf)
library(potential) 
library(sp)
library(kableExtra)
library(matrixStats)

# remotes::install_gitlab("dickoa/rhxl") ## rhdx dependency
# remotes::install_gitlab("dickoa/rhdx") ## github mirror also avalailable
library(rhdx)

library(gganimate)
library(cowplot)
library(transformr)

mainDir <- getwd()
## If you save your analysis under vignette folder...
#mainDirroot <- substring(mainDir, 0 , nchar(mainDir) - 10)
mainDirroot <- mainDir

```

 



## Leveraging Facebook data for Good dataset

People who use Facebook on a mobile device have the option of providing their precise location in order to enable products like Nearby Friends and Find Wi-Fi and to get local content and ads. Different type of products are produced by the [Facebok Data for Good Team]() by aggregating and de-identifying this data. Only people who opt in to Location History and background location collection are included. People with very few location pings in a day are not informative for these trends, and, therefore, we include only those people whose location is observed for a meaningful period of the day.

Central America indeed has an important [number of facebook users]and Facebook data for good has released a few [dataset](https://data.humdata.org/organization/facebook?groups=slv)

## How to re-use that script

Get the correct project name in HDX
